// constants/intervals.js - Interval constants for rule checking

export const INTERVALS = {
  UNISON: 0,
  MINOR_SECOND: 1,
  MAJOR_SECOND: 2,
  MINOR_THIRD: 3,
  MAJOR_THIRD: 4,
  PERFECT_FOURTH: 5,
  TRITONE: 6,
  PERFECT_FIFTH: 7,
  MINOR_SIXTH: 8,
  MAJOR_SIXTH: 9,
  MINOR_SEVENTH: 10,
  MAJOR_SEVENTH: 11,
  OCTAVE: 12
};

export const PERFECT_INTERVALS = [INTERVALS.UNISON, INTERVALS.PERFECT_FIFTH, INTERVALS.OCTAVE];
export const CONSONANT_INTERVALS = [
  INTERVALS.UNISON, INTERVALS.MINOR_THIRD, INTERVALS.MAJOR_THIRD,
  INTERVALS.PERFECT_FIFTH, INTERVALS.MINOR_SIXTH, INTERVALS.MAJOR_SIXTH, INTERVALS.OCTAVE
];
